# Generated by Django 2.0.7 on 2018-08-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parentName', models.CharField(blank=True, max_length=250, null=True)),
                ('tenantID', models.CharField(blank=True, max_length=250, null=True)),
                ('parentID', models.CharField(blank=True, max_length=250, null=True)),
                ('tenantDescription', models.CharField(blank=True, max_length=250, null=True)),
                ('leaf', models.BooleanField(default=False)),
                ('demoTenant', models.BooleanField(default=False)),
                ('installedVersion', models.CharField(blank=True, max_length=250, null=True)),
                ('lastUpdate', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantApps',
            fields=[
                ('appName', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TenantCloud',
            fields=[
                ('cloudName', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TenantConnections',
            fields=[
                ('connectionName', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TenantProducts',
            fields=[
                ('productName', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TenantServiceBoxName',
            fields=[
                ('serviceBoxName', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TenantUsers',
            fields=[
                ('userName', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='apps',
            field=models.ManyToManyField(to='cloudviewer.TenantApps'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cloud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudviewer.TenantCloud'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='products',
            field=models.ManyToManyField(to='cloudviewer.TenantProducts'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='serviceBox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudviewer.TenantServiceBoxName'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenantConnections',
            field=models.ManyToManyField(to='cloudviewer.TenantConnections'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='users',
            field=models.ManyToManyField(to='cloudviewer.TenantUsers'),
        ),
    ]
