# Generated by Django 2.0.7 on 2018-08-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='serviceBox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloudviewer.TenantServiceBoxName'),
        ),
    ]
